//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#pragma once

#include <memory>
#include <utility>
#include <vector>

#include "catalog/catalog_entry/catalog_entry.h"
#include "storage/index/index.h"
#include "storage/wal/record/wal_record_base.h"

namespace lbug {
namespace storage {

struct CreateIndexRecord final : WALRecord {
    catalog::CatalogEntry* catalogEntry;
    std::unique_ptr<catalog::CatalogEntry> ownedCatalogEntry;
    std::unique_ptr<IndexInfo> indexInfo;
    std::vector<uint8_t> treeBytes;

    CreateIndexRecord() : WALRecord{WALRecordType::CREATE_INDEX_RECORD}, catalogEntry{nullptr} {}
    CreateIndexRecord(catalog::CatalogEntry* catalogEntry, IndexInfo indexInfo,
        std::vector<uint8_t> treeBytes)
        : WALRecord{WALRecordType::CREATE_INDEX_RECORD}, catalogEntry{catalogEntry},
          indexInfo{std::make_unique<IndexInfo>(std::move(indexInfo))},
          treeBytes{std::move(treeBytes)} {}

    void serialize(common::Serializer& serializer) const override;
    static std::unique_ptr<CreateIndexRecord> deserialize(common::Deserializer& deserializer);
};

} // namespace storage
} // namespace lbug
