//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#pragma once

#include <memory>
#include <string>
#include <utility>
#include <vector>

#include "storage/wal/record/wal_record_base.h"

namespace lbug {
namespace storage {

struct LoadExtensionRecord final : WALRecord {
    std::string path;

    LoadExtensionRecord() : WALRecord{WALRecordType::LOAD_EXTENSION_RECORD} {}

    LoadExtensionRecord(std::string path)
        : WALRecord{WALRecordType::LOAD_EXTENSION_RECORD}, path{path} {}

    void serialize(common::Serializer& serializer) const override;
    static std::unique_ptr<LoadExtensionRecord> deserialize(common::Deserializer& deserializer);
};

} // namespace storage
} // namespace lbug
