//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#include "binder/binder.h"
#include "common/exception/runtime.h"
#include "common/serializer/deserializer.h"
#include "common/serializer/serializer.h"
#include "storage/wal/wal_record.h"

using namespace lbug::common;
using namespace lbug::binder;
namespace lbug {
namespace storage {

// Semi-manual serializer for TypeSpec union AlterExtraInfo, discriminated by
// alterType.
static void serializeAlterExtraInfo(Serializer& serializer, const BoundAlterInfo* alterInfo) {
    const auto* extraInfo = alterInfo->extraInfo.get();
    serializer.write(alterInfo->alterType);
    serializer.write(alterInfo->tableName);
    switch (alterInfo->alterType) {
    case AlterType::ADD_PROPERTY: {
        auto addInfo = extraInfo->constPtrCast<BoundExtraAddPropertyInfo>();
        addInfo->propertyDefinition.serialize(serializer);
    } break;
    case AlterType::DROP_PROPERTY: {
        auto dropInfo = extraInfo->constPtrCast<BoundExtraDropPropertyInfo>();
        serializer.write(dropInfo->propertyName);
    } break;
    case AlterType::RENAME_PROPERTY: {
        auto renamePropertyInfo = extraInfo->constPtrCast<BoundExtraRenamePropertyInfo>();
        serializer.write(renamePropertyInfo->newName);
        serializer.write(renamePropertyInfo->oldName);
    } break;
    case AlterType::COMMENT: {
        auto commentInfo = extraInfo->constPtrCast<BoundExtraCommentInfo>();
        serializer.write(commentInfo->comment);
    } break;
    case AlterType::RENAME: {
        auto renameTableInfo = extraInfo->constPtrCast<BoundExtraRenameTableInfo>();
        serializer.write(renameTableInfo->newName);
    } break;
    case AlterType::SET_SORTED_BY: {
        auto sortedByInfo = extraInfo->constPtrCast<BoundExtraSetSortedByInfo>();
        serializer.write(static_cast<uint64_t>(sortedByInfo->properties.size()));
        for (auto& property : sortedByInfo->properties) {
            serializer.write(property.propertyName);
            serializer.write(property.ascending);
        }
        serializer.write(sortedByInfo->csr);
        serializer.write(sortedByInfo->csrChangeEpoch);
    } break;
    case AlterType::ADD_FROM_TO_CONNECTION:
    case AlterType::DROP_FROM_TO_CONNECTION: {
        auto connectionInfo = extraInfo->constPtrCast<BoundExtraAlterFromToConnection>();
        serializer.write(connectionInfo->fromTableID);
        serializer.write(connectionInfo->toTableID);
    } break;
    default: {
        UNREACHABLE_CODE;
    }
    }
}

static decltype(auto) deserializeAlterRecord(Deserializer& deserializer) {
    auto alterType = AlterType::INVALID;
    std::string tableName;
    deserializer.deserializeValue(alterType);
    deserializer.deserializeValue(tableName);
    std::unique_ptr<BoundExtraAlterInfo> extraInfo;
    switch (alterType) {
    case AlterType::ADD_PROPERTY: {
        auto definition = PropertyDefinition::deserialize(deserializer);
        extraInfo = std::make_unique<BoundExtraAddPropertyInfo>(std::move(definition), nullptr);
    } break;
    case AlterType::DROP_PROPERTY: {
        std::string propertyName;
        deserializer.deserializeValue(propertyName);
        extraInfo = std::make_unique<BoundExtraDropPropertyInfo>(std::move(propertyName));
    } break;
    case AlterType::RENAME_PROPERTY: {
        std::string newName;
        std::string oldName;
        deserializer.deserializeValue(newName);
        deserializer.deserializeValue(oldName);
        extraInfo =
            std::make_unique<BoundExtraRenamePropertyInfo>(std::move(newName), std::move(oldName));
    } break;
    case AlterType::COMMENT: {
        std::string comment;
        deserializer.deserializeValue(comment);
        extraInfo = std::make_unique<BoundExtraCommentInfo>(std::move(comment));
    } break;
    case AlterType::RENAME: {
        std::string newName;
        deserializer.deserializeValue(newName);
        extraInfo = std::make_unique<BoundExtraRenameTableInfo>(std::move(newName));
    } break;
    case AlterType::SET_SORTED_BY: {
        uint64_t numProperties = 0;
        deserializer.deserializeValue(numProperties);
        std::vector<BoundSortedByProperty> properties;
        properties.reserve(numProperties);
        for (auto i = 0u; i < numProperties; ++i) {
            BoundSortedByProperty property;
            deserializer.deserializeValue(property.propertyName);
            deserializer.deserializeValue(property.ascending);
            properties.push_back(std::move(property));
        }
        bool csr = false;
        uint64_t csrChangeEpoch = 0;
        deserializer.deserializeValue(csr);
        deserializer.deserializeValue(csrChangeEpoch);
        auto sortedByInfo = std::make_unique<BoundExtraSetSortedByInfo>(std::move(properties), csr);
        sortedByInfo->csrChangeEpoch = csrChangeEpoch;
        extraInfo = std::move(sortedByInfo);
    } break;
    case AlterType::ADD_FROM_TO_CONNECTION:
    case AlterType::DROP_FROM_TO_CONNECTION: {
        table_id_t fromTableID = INVALID_TABLE_ID;
        table_id_t toTableID = INVALID_TABLE_ID;
        deserializer.deserializeValue(fromTableID);
        deserializer.deserializeValue(toTableID);
        extraInfo = std::make_unique<BoundExtraAlterFromToConnection>(fromTableID, toTableID);
    } break;
    default: {
        UNREACHABLE_CODE;
    }
    }
    return std::make_tuple(alterType, tableName, std::move(extraInfo));
}

void AlterTableEntryRecord::serialize(Serializer& serializer) const {
    WALRecord::serialize(serializer);
    serializeAlterExtraInfo(serializer, alterInfo);
}

std::unique_ptr<AlterTableEntryRecord> AlterTableEntryRecord::deserialize(
    Deserializer& deserializer) {
    auto [alterType, tableName, extraInfo] = deserializeAlterRecord(deserializer);
    auto retval = std::make_unique<AlterTableEntryRecord>();
    retval->ownedAlterInfo =
        std::make_unique<BoundAlterInfo>(alterType, tableName, std::move(extraInfo));
    return retval;
}

} // namespace storage
} // namespace lbug
