//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#include "common/serializer/deserializer.h"
#include "common/serializer/serializer.h"
#include "storage/wal/wal_record.h"

using namespace lbug::common;
namespace lbug {
namespace storage {

void CopyTableRecord::serialize(Serializer& serializer) const {
    WALRecord::serialize(serializer);
    serializer.write<table_id_t>(tableID);
}

std::unique_ptr<CopyTableRecord> CopyTableRecord::deserialize(Deserializer& deserializer) {
    table_id_t tableID = common::INVALID_TABLE_ID;
    if (deserializer.hasRemainingData()) {
        deserializer.deserializeValue<table_id_t>(tableID);
    }

    return std::make_unique<CopyTableRecord>(std::move(tableID));
}

} // namespace storage
} // namespace lbug
