//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#include "catalog/catalog_entry/catalog_entry.h"
#include "common/exception/runtime.h"
#include "common/serializer/deserializer.h"
#include "common/serializer/serializer.h"
#include "storage/wal/wal_record.h"

using namespace lbug::common;
using namespace lbug::catalog;
namespace lbug {
namespace storage {

// Semi-manual serializer for physical built-in index creation. The catalog entry uses the
// existing polymorphic catalog serialization; IndexInfo and tree bytes are storage payloads.
void CreateIndexRecord::serialize(Serializer& serializer) const {
    WALRecord::serialize(serializer);
    catalogEntry->serialize(serializer);
    indexInfo->serialize(serializer);
    serializer.write<uint64_t>(treeBytes.size());
    if (!treeBytes.empty()) {
        serializer.write(treeBytes.data(), treeBytes.size());
    }
}

std::unique_ptr<CreateIndexRecord> CreateIndexRecord::deserialize(Deserializer& deserializer) {
    auto retVal = std::make_unique<CreateIndexRecord>();
    retVal->ownedCatalogEntry = CatalogEntry::deserialize(deserializer);
    retVal->indexInfo = std::make_unique<IndexInfo>(IndexInfo::deserialize(deserializer));
    uint64_t treeSize = 0;
    deserializer.deserializeValue<uint64_t>(treeSize);
    retVal->treeBytes.resize(treeSize);
    if (treeSize > 0) {
        deserializer.read(retVal->treeBytes.data(), treeSize);
    }
    return retVal;
}

} // namespace storage
} // namespace lbug
