//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#include "common/serializer/deserializer.h"
#include "common/serializer/serializer.h"
#include "storage/wal/wal_record.h"

using namespace lbug::common;
namespace lbug {
namespace storage {

void DropCatalogEntryRecord::serialize(Serializer& serializer) const {
    WALRecord::serialize(serializer);
    serializer.write<oid_t>(entryID);
    serializer.write<catalog::CatalogEntryType>(entryType);
}

std::unique_ptr<DropCatalogEntryRecord> DropCatalogEntryRecord::deserialize(
    Deserializer& deserializer) {
    oid_t entryID = common::INVALID_OID;
    if (deserializer.hasRemainingData()) {
        deserializer.deserializeValue<oid_t>(entryID);
    }
    catalog::CatalogEntryType entryType{};
    if (deserializer.hasRemainingData()) {
        deserializer.deserializeValue<catalog::CatalogEntryType>(entryType);
    }

    return std::make_unique<DropCatalogEntryRecord>(std::move(entryID), std::move(entryType));
}

} // namespace storage
} // namespace lbug
