//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#include "common/serializer/deserializer.h"
#include "common/serializer/serializer.h"
#include "storage/wal/wal_record.h"

using namespace lbug::common;
namespace lbug {
namespace storage {

void LoadExtensionRecord::serialize(Serializer& serializer) const {
    WALRecord::serialize(serializer);
    serializer.writeDebuggingInfo("path");
    serializer.write<std::string>(path);
}

std::unique_ptr<LoadExtensionRecord> LoadExtensionRecord::deserialize(Deserializer& deserializer) {
    std::string key;
    std::string path{};
    if (deserializer.hasRemainingData()) {
        deserializer.validateDebuggingInfo(key, "path");
        deserializer.deserializeValue<std::string>(path);
    }

    return std::make_unique<LoadExtensionRecord>(std::move(path));
}

} // namespace storage
} // namespace lbug
