//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#include "common/serializer/deserializer.h"
#include "common/serializer/serializer.h"
#include "main/client_context.h"
#include "storage/buffer_manager/memory_manager.h"
#include "storage/wal/wal_record.h"

using namespace lbug::common;
namespace lbug {
namespace storage {

void NodeUpdateRecord::serialize(Serializer& serializer) const {
    WALRecord::serialize(serializer);
    serializer.writeDebuggingInfo("table_id");
    serializer.write<table_id_t>(tableID);
    serializer.writeDebuggingInfo("column_id");
    serializer.write<column_id_t>(columnID);
    serializer.writeDebuggingInfo("node_offset");
    serializer.write<offset_t>(nodeOffset);
    serializer.writeDebuggingInfo("property_vector");
    propertyVector->serialize(serializer);
}

std::unique_ptr<NodeUpdateRecord> NodeUpdateRecord::deserialize(Deserializer& deserializer,
    const main::ClientContext& clientContext) {
    std::string key;
    table_id_t tableID = INVALID_TABLE_ID;
    if (deserializer.hasRemainingData()) {
        deserializer.validateDebuggingInfo(key, "table_id");
        deserializer.deserializeValue<table_id_t>(tableID);
    }
    column_id_t columnID = INVALID_COLUMN_ID;
    if (deserializer.hasRemainingData()) {
        deserializer.validateDebuggingInfo(key, "column_id");
        deserializer.deserializeValue<column_id_t>(columnID);
    }
    offset_t nodeOffset = INVALID_OFFSET;
    if (deserializer.hasRemainingData()) {
        deserializer.validateDebuggingInfo(key, "node_offset");
        deserializer.deserializeValue<offset_t>(nodeOffset);
    }
    std::unique_ptr<ValueVector> propertyVector;
    if (deserializer.hasRemainingData()) {
        deserializer.validateDebuggingInfo(key, "property_vector");
        auto propertyVectorState = std::make_shared<DataChunkState>();
        propertyVector = ValueVector::deSerialize(deserializer, MemoryManager::Get(clientContext),
            propertyVectorState);
    }

    return std::make_unique<NodeUpdateRecord>(std::move(tableID), std::move(columnID),
        std::move(nodeOffset), std::move(propertyVector));
}

} // namespace storage
} // namespace lbug
