//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#include "common/serializer/deserializer.h"
#include "common/serializer/serializer.h"
#include "main/client_context.h"
#include "storage/buffer_manager/memory_manager.h"
#include "storage/wal/wal_record.h"

using namespace lbug::common;
namespace lbug {
namespace storage {

void NodeDeletionRecord::serialize(Serializer& serializer) const {
    WALRecord::serialize(serializer);
    serializer.writeDebuggingInfo("table_id");
    serializer.write<table_id_t>(tableID);
    serializer.writeDebuggingInfo("node_offset");
    serializer.write<offset_t>(nodeOffset);
    serializer.writeDebuggingInfo("pk_vector");
    pkVector->serialize(serializer);
}

std::unique_ptr<NodeDeletionRecord> NodeDeletionRecord::deserialize(Deserializer& deserializer,
    const main::ClientContext& clientContext) {
    std::string key;
    table_id_t tableID = INVALID_TABLE_ID;
    if (deserializer.hasRemainingData()) {
        deserializer.validateDebuggingInfo(key, "table_id");
        deserializer.deserializeValue<table_id_t>(tableID);
    }
    offset_t nodeOffset = INVALID_OFFSET;
    if (deserializer.hasRemainingData()) {
        deserializer.validateDebuggingInfo(key, "node_offset");
        deserializer.deserializeValue<offset_t>(nodeOffset);
    }
    std::unique_ptr<ValueVector> pkVector;
    if (deserializer.hasRemainingData()) {
        deserializer.validateDebuggingInfo(key, "pk_vector");
        auto pkVectorState = std::make_shared<DataChunkState>();
        pkVector = ValueVector::deSerialize(deserializer, MemoryManager::Get(clientContext),
            pkVectorState);
    }

    return std::make_unique<NodeDeletionRecord>(std::move(tableID), std::move(nodeOffset),
        std::move(pkVector));
}

} // namespace storage
} // namespace lbug
