//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#include "common/serializer/deserializer.h"
#include "common/serializer/serializer.h"
#include "main/client_context.h"
#include "storage/buffer_manager/memory_manager.h"
#include "storage/wal/wal_record.h"

using namespace lbug::common;
namespace lbug {
namespace storage {

void RelDetachDeleteRecord::serialize(Serializer& serializer) const {
    WALRecord::serialize(serializer);
    serializer.writeDebuggingInfo("table_id");
    serializer.write<table_id_t>(tableID);
    serializer.writeDebuggingInfo("direction");
    serializer.write<RelDataDirection>(direction);
    serializer.writeDebuggingInfo("src_node_vector");
    srcNodeIDVector->serialize(serializer);
}

std::unique_ptr<RelDetachDeleteRecord> RelDetachDeleteRecord::deserialize(
    Deserializer& deserializer, const main::ClientContext& clientContext) {
    std::string key;
    table_id_t tableID = INVALID_TABLE_ID;
    if (deserializer.hasRemainingData()) {
        deserializer.validateDebuggingInfo(key, "table_id");
        deserializer.deserializeValue<table_id_t>(tableID);
    }
    RelDataDirection direction = RelDataDirection::INVALID;
    if (deserializer.hasRemainingData()) {
        deserializer.validateDebuggingInfo(key, "direction");
        deserializer.deserializeValue<RelDataDirection>(direction);
    }
    std::unique_ptr<ValueVector> srcNodeIDVector;
    if (deserializer.hasRemainingData()) {
        deserializer.validateDebuggingInfo(key, "src_node_vector");
        auto srcNodeIDVectorState = std::make_shared<DataChunkState>();
        srcNodeIDVector = ValueVector::deSerialize(deserializer, MemoryManager::Get(clientContext),
            srcNodeIDVectorState);
    }

    return std::make_unique<RelDetachDeleteRecord>(std::move(tableID), std::move(direction),
        std::move(srcNodeIDVector));
}

} // namespace storage
} // namespace lbug
