//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_wal_typespec.py.
// Do not edit this file manually.
//===----------------------------------------------------------------------===//

#include "common/serializer/deserializer.h"
#include "common/serializer/serializer.h"
#include "storage/wal/wal_record.h"

using namespace lbug::common;
namespace lbug {
namespace storage {

void UpdateSequenceRecord::serialize(Serializer& serializer) const {
    WALRecord::serialize(serializer);
    serializer.write<sequence_id_t>(sequenceID);
    serializer.write<uint64_t>(kCount);
}

std::unique_ptr<UpdateSequenceRecord> UpdateSequenceRecord::deserialize(
    Deserializer& deserializer) {
    sequence_id_t sequenceID = 0;
    if (deserializer.hasRemainingData()) {
        deserializer.deserializeValue<sequence_id_t>(sequenceID);
    }
    uint64_t kCount = 0;
    if (deserializer.hasRemainingData()) {
        deserializer.deserializeValue<uint64_t>(kCount);
    }

    return std::make_unique<UpdateSequenceRecord>(std::move(sequenceID), std::move(kCount));
}

} // namespace storage
} // namespace lbug
